### ISSUE TITLE
Error: Failed to refresh drive credentials.

### ISSUE THREAD

**Issue by Endijuan33** [sixgpt/miner#38]
sixgpt3-1  | Request failed with status code 400
sixgpt3-1  | Error uploading to drive Error: Failed to refresh drive credentials.
sixgpt3-1  |     at SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:91:23)
sixgpt3-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async DriveRepository.getActiveAccount (/usr/src/app/dist/repositories/drive.repository.js:45:17)
sixgpt3-1  |     at async DriveRepository.upload (/usr/src/app/dist/repositories/drive.repository.js:84:23)
sixgpt3-1  |     at async DriveRepository.uploadWithRetry (/usr/src/app/dist/repositories/drive.repository.js:71:24)
sixgpt3-1  | Sleeping 5 MINS for attempt 1 to pass google cloud timeout...
sixgpt3-1  | refreshing drive credentials
sixgpt3-1  | Request failed with status code 400
sixgpt3-1  | Failed to refresh drive credentials.
sixgpt3-1  | /usr/src/app/dist/repositories/sixgpt.repository.js:91
sixgpt3-1  |                 throw new Error('Failed to refresh drive credentials.');
sixgpt3-1  |                       ^
sixgpt3-1  |
sixgpt3-1  | Error: Failed to refresh drive credentials.
sixgpt3-1  |     at SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:91:23)
sixgpt3-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async SixgptUserRepository.refreshDriveCredentials (/usr/src/app/dist/repositories/sixgpt.repository.js:100:24)
sixgpt3-1  |     at async DriveRepository.getActiveAccount (/usr/src/app/dist/repositories/drive.repository.js:45:17)
sixgpt3-1  |     at async DriveRepository.uploadWithRetry (/usr/src/app/dist/repositories/drive.repository.js:77:38)
sixgpt3-1  |     at async AppService.run (/usr/src/app/dist/app.service.js:58:29)
sixgpt3-1  |
sixgpt3-1  | Node.js v22.0.0
sixgpt3-1 exited with code 1

**Comment by dedekganteng** [comment]
same problem here, anyone already fix this issue?
