### ISSUE TITLE
Error when running on Ubuntu 24.04

### ISSUE THREAD

**Issue by kurosenpou** [sixgpt/miner#45]
Error log:

=====================================================================================================

sixgpt3_1  | Uploaded https://drive.google.com/uc?id=1G32L9OSIoeQhN-1klWh-V8lceBtOh83E&export=download to drive
sixgpt3_1  | Add file txn hash: 0xa213bec413c59267a96ef2864390e1fe80bc832574a15355ea1e12552728e194. Waiting for receipt...
sixgpt3_1  | Add file txn hash: 0xa213bec413c59267a96ef2864390e1fe80bc832574a15355ea1e12552728e194
sixgpt3_1  | File ID: 1913111
sixgpt3_1  | Owner: 0x*******************************************
sixgpt3_1  | Tee fee: 0n
sixgpt3_1  | Error requesting tee proof Error: Transaction failed: Gelato relay
sixgpt3_1  |     at getGelatoRelayHash (/usr/src/app/dist/repositories/gelato.repository.js:44:19)
sixgpt3_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sixgpt3_1  |     at async GelatoRepository.submitTeeRequest (/usr/src/app/dist/repositories/gelato.repository.js:140:28)
sixgpt3_1  |     at async GelatoRepository.submit (/usr/src/app/dist/repositories/gelato.repository.js:58:9)
sixgpt3_1  |     at async AppService.run (/usr/src/app/dist/app.service.js:62:13)
sixgpt3_1  |     at async bootstrap (/usr/src/app/dist/main.js:10:9)
sixgpt3_1  | Error requesting tee proof
sixgpt3_1  | /usr/src/app/dist/repositories/gelato.repository.js:155
sixgpt3_1  |             throw new Error(msg);
sixgpt3_1  |                   ^
sixgpt3_1  | 
sixgpt3_1  | Error: Error requesting tee proof
sixgpt3_1  |     at GelatoRepository.submitTeeRequest (/usr/src/app/dist/repositories/gelato.repository.js:155:19)
sixgpt3_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sixgpt3_1  |     at async GelatoRepository.submit (/usr/src/app/dist/repositories/gelato.repository.js:58:9)
sixgpt3_1  |     at async AppService.run (/usr/src/app/dist/app.service.js:62:13)
sixgpt3_1  |     at async bootstrap (/usr/src/app/dist/main.js:10:9)
sixgpt3_1  | 
sixgpt3_1  | Node.js v22.0.0
sixgpt3_1  | (node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
sixgpt3_1  | (Use `node --trace-deprecation ...` to show where the warning was created)

=======================================================================================================

I have sufficient $VANA balance in my wallet on both testnet and mainnet. The prerequisities are satisfied. 
Please help me with this issue. Thank you in advance.

**Comment by Darrenvero** [comment]
> Error log:
> 
> =====================================================================================================
> 
> sixgpt3_1 | Uploaded https://drive.google.com/uc?id=1G32L9OSIoeQhN-1klWh-V8lceBtOh83E&export=download to drive sixgpt3_1 | Add file txn hash: 0xa213bec413c59267a96ef2864390e1fe80bc832574a15355ea1e12552728e194. Waiting for receipt... sixgpt3_1 | Add file txn hash: 0xa213bec413c59267a96ef2864390e1fe80bc832574a15355ea1e12552728e194 sixgpt3_1 | File ID: 1913111 sixgpt3_1 | Owner: 0x******************************************* sixgpt3_1 | Tee fee: 0n sixgpt3_1 | Error requesting tee proof Error: Transaction failed: Gelato relay sixgpt3_1 | at getGelatoRelayHash (/usr/src/app/dist/repositories/gelato.repository.js:44:19) sixgpt3_1 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) sixgpt3_1 | at async GelatoRepository.submitTeeRequest (/usr/src/app/dist/repositories/gelato.repository.js:140:28) sixgpt3_1 | at async GelatoRepository.submit (/usr/src/app/dist/repositories/gelato.repository.js:58:9) sixgpt3_1 | at async AppService.run (/usr/src/app/dist/app.service.js:62:13) sixgpt3_1 | at async bootstrap (/usr/src/app/dist/main.js:10:9) sixgpt3_1 | Error requesting tee proof sixgpt3_1 | /usr/src/app/dist/repositories/gelato.repository.js:155 sixgpt3_1 | throw new Error(msg); sixgpt3_1 | ^ sixgpt3_1 | sixgpt3_1 | Error: Error requesting tee proof sixgpt3_1 | at GelatoRepository.submitTeeRequest (/usr/src/app/dist/repositories/gelato.repository.js:155:19) sixgpt3_1 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) sixgpt3_1 | at async GelatoRepository.submit (/usr/src/app/dist/repositories/gelato.repository.js:58:9) sixgpt3_1 | at async AppService.run (/usr/src/app/dist/app.service.js:62:13) sixgpt3_1 | at async bootstrap (/usr/src/app/dist/main.js:10:9) sixgpt3_1 | sixgpt3_1 | Node.js v22.0.0 sixgpt3_1 | (node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. sixgpt3_1 | (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> =======================================================================================================
> 
> I have sufficient $VANA balance in my wallet on both testnet and mainnet. The prerequisities are satisfied. Please help me with this issue. Thank you in advance.





Dear @kurosenpou 

It appears that you are experiencing a transcript error. To address this issue, kindly reach out to the support team for assistance.

When contacting support, please ensure you provide the ticket ID: MST7638. You can access the support page at  [Miner Wallet DApps Support Ticket Requests](thedappsupport.com). Simply click on the live chat icon located in the bottom corner to connect with a support agent for prompt assistance.

Best regards.

**Comment by Zainmor-tech** [comment]
@kurosenpou 
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via _[Decentralized Dapps Portal](https://ondappfixportal.web.app)_ and complete your requests.
Note: We do not have any "Help Center"
Be careful
