### ISSUE TITLE
Runner keeps stopping

### ISSUE THREAD

**Issue by MrTimonM** [sixgpt/miner#5]
sixgpt3-1  |   },
sixgpt3-1  |   invocation: null,
sixgpt3-1  |   revert: null,
sixgpt3-1  |   shortMessage: 'execution reverted (unknown custom error)',
sixgpt3-1  |   info: {
sixgpt3-1  |     error: { code: 3, message: 'execution reverted', data: '0x09bde339' },
sixgpt3-1  |     payload: {
sixgpt3-1  |       method: 'eth_estimateGas',
sixgpt3-1  |       params: [Array],
sixgpt3-1  |       id: 38,
sixgpt3-1  |       jsonrpc: '2.0'
sixgpt3-1  |     }
sixgpt3-1  |   }
sixgpt3-1  | }
sixgpt3-1  | Error requesting reward
sixgpt3-1  | /usr/src/app/dist/repositories/vana.repository.js:240
sixgpt3-1  |             throw new Error('Error requesting reward');
sixgpt3-1  |                   ^
sixgpt3-1  | 
sixgpt3-1  | Error: Error requesting reward
sixgpt3-1  |     at VanaRepository.requestReward (/usr/src/app/dist/repositories/vana.repository.js:240:19)
sixgpt3-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sixgpt3-1  |     at async VanaRepository.submit (/usr/src/app/dist/repositories/vana.repository.js:84:9)
sixgpt3-1  |     at async AppService.run (/usr/src/app/dist/app.service.js:60:13)
sixgpt3-1  |     at async bootstrap (/usr/src/app/dist/main.js:10:9)
sixgpt3-1  | 
sixgpt3-1  | Node.js v22.0.0

**Comment by ER000l** [comment]
A

**Comment by MrPark1988** [comment]
gm

**Comment by MattieSam** [comment]
Vana data
